// Generated by scripts/ingestCorpus.mjs. Do not edit by hand.
export const corpusInsights = {
  "source": "Tourism-Neuroclient-OBS",
  "generatedAt": "2026-07-31T14:58:51.544012+00:00",
  "totalCalls": 2359,
  "wazzupDialogs": 2356,
  "audioHours": 150.2,
  "averageScore": 36.7,
  "trainingMaterials": {
    "total": 28,
    "salesScripts": 14,
    "selectionMethodology": 3,
    "countryVietnam": 3,
    "countryThailand": 2,
    "countryUae": 1
  },
  "mainArchetypes": [
    {
      "id": "price_sensitive",
      "label": "Чувствителен к цене",
      "share": 62.2,
      "trigger": "после сухой цены без объяснения вилки и альтернатив"
    },
    {
      "id": "thinking_budget_unclear",
      "label": "Думает, бюджет неясен",
      "share": 20.7,
      "trigger": "если агент отпускает “подумаю” без следующего шага"
    },
    {
      "id": "silent_busy_unreachable",
      "label": "Занят / пропадает",
      "share": 10.9,
      "trigger": "если не зафиксировать точное время перезвона"
    },
    {
      "id": "family_age_constraints",
      "label": "Семья и возрастные ограничения",
      "share": 1.9,
      "trigger": "если агент предлагает отель без учёта семьи/возраста"
    }
  ],
  "sourceCoverage": {
    "calls": 2359,
    "wazzupDealFiles": 2356,
    "trainingMaterials": 28,
    "reports": 1,
    "wazzupAnalysisReports": 3
  },
  "wazzupSuccessSignals": [
    {
      "id": "risk_honesty",
      "label": "Риски проговорены честно",
      "success": 88.1,
      "lost": 41.1
    },
    {
      "id": "payment_booking",
      "label": "Бронь/оплата объяснены пошагово",
      "success": 82.1,
      "lost": 28.4
    },
    {
      "id": "sets_next_step",
      "label": "Есть следующий шаг",
      "success": 74.4,
      "lost": 43.5
    },
    {
      "id": "reviews_fear",
      "label": "Страх отзывов обработан",
      "success": 51.2,
      "lost": 17.5
    },
    {
      "id": "thinking_objection",
      "label": "“Подумаю” не отпущено в пустоту",
      "success": 45.8,
      "lost": 13.8
    }
  ],
  "silenceTriggers": [
    {
      "label": "после поверхностного разговора без вводных",
      "share": 97.5
    },
    {
      "label": "после цены или несовпадения бюджета с реальностью",
      "share": 90.5
    },
    {
      "label": "после отсутствия 2–3 альтернатив",
      "share": 52.9
    },
    {
      "label": "после разговора без конкретного следующего шага",
      "share": 20
    }
  ],
  "rulePacks": [
    {
      "id": "next_step_deadline",
      "source": "Training Materials/sales_scripts__framework-nextstep__e886c31cd4d5b8ac.md",
      "rule": "каждая подборка заканчивается действием, временем и каналом"
    },
    {
      "id": "price_fork",
      "source": "Reports/Neuroclient Brain - Full Report.md",
      "rule": "цена объясняется вилкой, а не одной сухой стоимостью"
    },
    {
      "id": "objection_script",
      "source": "Training Materials/sales_scripts__script-objections-tel-2024__bc882c39ea6c5cb8.md",
      "rule": "возражение разбирается через сравнение и следующий шаг"
    },
    {
      "id": "selection_checklist",
      "source": "Training Materials/selection_methodology__Чек-лист-идеальная-подборка__8d233c5504905b21.md",
      "rule": "подборка должна показывать плюсы, минусы и кому вариант не подходит"
    },
    {
      "id": "reviews_fact_signal_conclusion",
      "source": "Wazzup Dialogs/Русские отчёты/Русский отчёт по 2356 Wazzup amoCRM диалогам.txt",
      "rule": "отзывы раскладываются как факт / отзывный сигнал / вывод"
    }
  ],
  "behaviorRules": [
    "Do not start with a perfect brief. Start with “мы пока смотрим”, “до 200”, “куда можно”, “мне неудобно”, “вы по какому вопросу?”.",
    "Reveal progressively. Give dates/budget/family only when the agent asks specifically.",
    "Accept a polite process promise once. If agent says “подберу/проверю”, accept, but expect a concrete next step.",
    "Go silent after vague endings. If there is no time/channel/decision step, move toward silence.",
    "Treat price as a fork, not a wall. If agent explains compromises, stay engaged; if only “дорого/невозможно”, cool down.",
    "Family/age clients buy safety. Push them through comfort/risk reduction, not discount.",
    "Document blockers need a calendar. Do not simulate them as simple refusals; they return if follow-up is timed."
  ]
};

export const sourceRefs = {
  "familyTurkey": [
    {
      "sourceType": "report",
      "path": "Tourism-Neuroclient-OBS/Reports/Neuroclient Brain - Full Report.md",
      "confidence": "high"
    },
    {
      "sourceType": "training_material",
      "path": "Tourism-Neuroclient-OBS/Training Materials/selection_methodology__Чек-лист-идеальная-подборка__8d233c5504905b21.md",
      "confidence": "medium"
    },
    {
      "sourceType": "wazzup_dialog",
      "path": "Tourism-Neuroclient-OBS/Wazzup Dialogs/Русские отчёты/Русский отчёт по 2356 Wazzup amoCRM диалогам.txt",
      "confidence": "medium"
    }
  ],
  "egyptPrice": [
    {
      "sourceType": "report",
      "path": "Tourism-Neuroclient-OBS/Reports/Neuroclient Brain - Full Report.md",
      "confidence": "high"
    },
    {
      "sourceType": "training_material",
      "path": "Tourism-Neuroclient-OBS/Training Materials/sales_scripts__script-objections-tel-2024__bc882c39ea6c5cb8.md",
      "confidence": "high"
    },
    {
      "sourceType": "wazzup_dialog",
      "path": "Tourism-Neuroclient-OBS/Wazzup Dialogs/Analysis/Neuroclient Behavior Model - Wazzup Update.md",
      "confidence": "medium"
    }
  ],
  "uaePremium": [
    {
      "sourceType": "wazzup_dialog",
      "path": "Tourism-Neuroclient-OBS/Wazzup Dialogs/Русские отчёты/Русский отчёт по 2356 Wazzup amoCRM диалогам.txt",
      "confidence": "high"
    },
    {
      "sourceType": "training_material",
      "path": "Tourism-Neuroclient-OBS/Training Materials/country_uae__25-UAE-pamytka__970781855f2e9aa7.md",
      "confidence": "medium"
    },
    {
      "sourceType": "training_material",
      "path": "Tourism-Neuroclient-OBS/Training Materials/selection_methodology__Чек-лист-идеальная-подборка__8d233c5504905b21.md",
      "confidence": "medium"
    }
  ]
};
